FROM node:16-alpine AS deps

ENV NODE_ENV=production

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --forzen-lockfile

# Rebuild the source code only when needed
FROM node:16-alpine AS builder

ENV NODE=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system -uid 1001 nextjs