import Head from 'next/head';
import Catcard from '../components/cards/cat/Catcard';
import { mockCatcardProps } from '../components/cards/cat/Catcard.mocks';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import SidebarLayout from '../components/layouts/sidebar/SidebarLayout';
import styles from '../styles/Home.module.css';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello Staff Students APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-gradient-to-t from-cyan-500 to-blue-500">
        <h1>Welcom to next staff</h1>
        <Catcard {...mockCatcardProps.base} />
      </section>
    </div>
  );
};

export default Home;

Home.getLayout = function getLayout(page: JSX.Element) {
  return (
    <PrimaryLayout>
      <SidebarLayout />
      {page}
    </PrimaryLayout>
  );
};
